name: Build beta

on:
  push:
    branches-ignore:
    - main

jobs:
  # unit-tests:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  sast-scanner:
    name: Run SAST scanners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bandit
        run: |
          sudo pip install bandit

      - name: Run bandit SAST
        run: |
            bandit -r . -f html -o bandit-raport.html 
            
  # https://github.com/marketplace/actions/build-and-push-docker-images
  build-and-publish:
    name: Build and publish beta image
    needs: [sast-scanner]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:beta