name: Build beta

on:
  push:
    branches-ignore:
    - main

jobs:
  # unit-tests:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  # sast-scanner:
  #   name: Run SAST scanners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install bandit
  #       run: |
  #         sudo pip install bandit

  #     - name: Run bandit SAST
  #       run: |
  #           bandit -r . -f html -o bandit-raport.html 

  # https://github.com/marketplace/actions/build-and-push-docker-images
  dast-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional but useful for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker Image (no push)
      - name: Build Docker Image
        run: |
          docker build -t book_app .

      # Step 4: Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name book_app book_app

      # Step 5: Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'http://localhost:5000'
          fail_action: true
        env:
          JAVA_OPTS: '-Xmx512m'

      # Step 6: Stop and Clean Up Docker Container
      - name: Stop and Remove Container
        if: always()
        run: |
          docker stop book_app
          docker rm book_app
  
  build-and-publish:
    name: Build and publish beta image
    # needs: [sast-scanner]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:beta
