name: Build beta

on:
  push:
    branches-ignore:
    - main

jobs:
  # unit-tests:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  # sast-scanner:
  #   name: Run SAST scanners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install bandit
  #       run: |
  #         sudo pip install bandit

  #     - name: Run bandit SAST
  #       run: |
  #           bandit -r . -f html -o bandit-raport.html 

  sca-scanner:
    name: Run SCA OWASP scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install OWASP SCA
        run: |
          curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v12.0.1/dependency-check-12.0.1-release.zip" --output dependency-check.zip

      - name: Run OWASP SCA
        run: |
          ./bin/dependency-check.sh \
          --project "Python project" \
          --scan . \
          --out sca-raport \
          --format ALL

      - name: Upload SCA report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SCA raport
          path: sca-raport/

  # https://github.com/marketplace/actions/build-and-push-docker-images
  build-and-publish:
    name: Build and publish beta image
    # needs: [sast-scanner]
    needs: [sca-scanner]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:beta