name: Build beta

on:
  push:
    branches-ignore:
    - main

jobs:
  # unit-tests:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  # sast-scanner:
  #   name: Run SAST scanners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install bandit
  #       run: |
  #         sudo pip install bandit

  #     - name: Run bandit SAST
  #       run: |
  #           bandit -r . -f html -o bandit-raport.html 

  # https://github.com/marketplace/actions/build-and-push-docker-images
  zap-scan:
    name: OWASP ZAP Scan - DAST
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Start Test Environment
      run: |
        docker build -t book_app
        docker-compose up -d -p 5000:5000 --name book_app book_app

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.8.0
      with:
        target: 'http://localhost:5000'
        fail_action: true # Set to false to prevent failures from blocking the pipeline
      env:
        JAVA_OPTS: '-Xmx512m'

    - name: View OWASP ZAP Report
      if: always()
      run: cat zap.out
  
  build-and-publish:
    name: Build and publish beta image
    # needs: [sast-scanner]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:beta
