name: Build main

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  sast-scanner:
    name: Run SAST scanners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bandit
        if: always()
        run: |
          sudo pip install bandit

      - name: Run bandit SAST
        run: |
            bandit -r . -f html -o bandit-raport.html 
        
      - name: Upload bandit raport
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit raport
          path: bandit-raport.html
  
  sca-scanner:
    runs-on: ubuntu-latest
    name: pupio/safety SCA scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pupio/safety scan
        run: |
          set -x
          docker run -v ${{github.workspace}}:/sources pyupio/safety safety check -r /sources/requirements.txt --full-report


# Miejsce na testy
  build-and-publish:
    name: Build and publish latest image
    needs: [sast-scanner, sca-scanner]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:latest