name: Build main

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
        continue-on-error: true

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: .pytest_cache  # Upload pytest cache or logs if configured

  # sast-scanner:
  #   name: Run SAST scanners
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install bandit
  #       if: always()
  #       run: |
  #         sudo pip install bandit

  #     - name: Run bandit SAST
  #       run: |
  #           bandit -r . -f html -o bandit-raport.html 

  #     - name: Upload bandit raport
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: bandit raport
  #         path: bandit-raport.html

  zap-scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication for DAST
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Start Application
        run: |
          docker build -t tbo-app .
          docker run -d -p 5000:5000 --name tbo-app tbo-app
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          allow_issue_writing: false
          cmd_options: '-a'

  build-and-publish:
    name: Build and publish latest image
    needs: [pytest,  zap-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tbo-project-hub:latest
